name: Forward Webhook

on:
  push:
    branches:
      - main  # Or the branch you want to monitor

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger repository dispatch
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/dparvin/PropertyGridHelpers/dispatches \
        -d '{"event_type": "update-gh-pages"}'
